/**
 * Projekte, Labs und Archiv — englische Fassung (Übersetzungsentwurf) von content/projects.ts.
 * Gleiche Struktur/IDs wie die deutsche Datei; übersetzt sind nur Texte. Wird in LD Flow als ENTWURF angelegt und
 * erst nach Prüfung veröffentlicht.
 */

import type { Project, ProjectKind } from '../projects';

export const PROJECTS: Project[] = [
  {
    "id": "corefall",
    "kind": "labs",
    "kat": "Game",
    "tag": "AI EXPERIMENT",
    "datum": "05/2026",
    "name": "Corefall",
    "mono": "CF",
    "color": "#C2410C",
    "featured": true,
    "link": "https://bjoern-sellnau.github.io/core-fall/",
    "tool": "Claude Code · Opus 4.7 · Claude Design",
    "desc": "A 6DoF shooter in the vein of Descent — full freedom of movement, retro soul, modern stack.",
    "ueberblick": "A 6DoF shooter in the spirit of Descent: fly, roll, yaw — full freedom of movement in every direction, right in the browser.",
    "ansatz": "Built as an AI experiment: Claude Code with Opus 4.7 as pair programmer, Claude Design for the visual direction. Iterative — playable core first, then feel, then polish.",
    "stack": [
      "Claude Code",
      "Opus 4.7",
      "Claude Design",
      "JavaScript",
      "Canvas/WebGL"
    ],
    "ergebnis": "Playable in the browser. The fastest way to grasp what AI-assisted game development feels like in 2026.",
    "zitat": "Six degrees of freedom don't forgive sloppy math.",
    "learnings": "Quaternions early, UI late — and game feel happens in the last ten percent. The AI partner speeds up the first ninety."
  },
  {
    "id": "covert",
    "kind": "labs",
    "kat": "Game",
    "tag": "AI EXPERIMENT",
    "datum": "04/2026",
    "name": "Covert Operations",
    "mono": "CO",
    "color": "#14532D",
    "featured": true,
    "link": "https://bjoern-sellnau.github.io/Covert-Operations/",
    "tool": "Claude Code · Opus 4.7 · Claude Design",
    "desc": "Top-down, iso and FPS shooter in one — one playing field, many perspectives.",
    "ueberblick": "One shooter, three perspectives: top-down, isometric and first-person — the same playing field, switchable.",
    "ansatz": "Switching perspectives as an architecture exercise: one game logic, several renderers. Claude Code handled the grunt work, the decisions stayed human.",
    "stack": [
      "Claude Code",
      "Opus 4.7",
      "Claude Design",
      "JavaScript",
      "Canvas"
    ],
    "ergebnis": "Playable in the browser — and the blueprint for the Arena spin-off.",
    "zitat": "One game logic, three cameras — architecture pays off in perspectives.",
    "learnings": "Keeping renderers swappable costs one day and saves three. Switching perspectives isn't a feature, it's an architecture test."
  },
  {
    "id": "openbooking",
    "kind": "archiv",
    "kat": "Professional",
    "tag": "LEAD FRONTEND",
    "datum": "2016–2020",
    "name": "OpenBooking",
    "mono": "OB",
    "color": "#1E3A5F",
    "featured": true,
    "tool": "PIXELTEX GmbH · OpenBooking AG",
    "desc": "Hotel & accommodation meta search — Lead Developer Frontend & Mobile Solutions.",
    "ueberblick": "The hotel and accommodation meta search by PIXELTEX and OpenBooking AG.",
    "ansatz": "From September 2016, responsible as Lead Developer for Frontend and Mobile Solutions — architecture, implementation, delivery.",
    "stack": [
      "JavaScript",
      "Frontend architecture",
      "Mobile",
      "Node"
    ],
    "ergebnis": "Four years of ownership of the most visible part of the product.",
    "zitat": "Meta search means: other people's data, your own responsibility.",
    "learnings": "Being lead means typing less and deciding more — and setting standards that work even without you."
  },
  {
    "id": "egov",
    "kind": "archiv",
    "kat": "Professional",
    "tag": "ENTERPRISE",
    "datum": "since 2026",
    "name": "E-Government & Customs",
    "mono": "EG",
    "color": "#0F2137",
    "featured": false,
    "tool": "Materna SE — #TeamMaterna",
    "desc": "Public sector applications at Materna. Details under NDA.",
    "ueberblick": "Specialist applications for the public sector — e-government and customs — as a Senior Developer at Materna.",
    "ansatz": "React and TypeScript in an enterprise setting: long-lived, accessible, maintainable. The NDA doesn't allow more.",
    "stack": [
      "React",
      "TypeScript",
      "Enterprise",
      "Public Sector"
    ],
    "ergebnis": "Software that public administration actually uses.",
    "zitat": "Government software is good when nobody talks about it.",
    "learnings": "Accessibility and maintainability are features, not requirements imposed from outside — in the public sector, longevity determines value."
  },
  {
    "id": "neuewebsite",
    "kind": "projekte",
    "kat": "Website",
    "tag": "RELAUNCH",
    "datum": "coming soon",
    "name": "New Website",
    "mono": "L!",
    "color": "#D97706",
    "featured": true,
    "tool": "Claude Code · Claude Design",
    "desc": "The relaunch of loona-designs.de — Liquid Glass, View Transitions and AI in the process.",
    "ueberblick": "After the DesignUpdates of 2011, 2015 and 2016, the biggest cut yet: loona-designs.de is being rethought — as a portfolio platform with projects, labs and blog.",
    "ansatz": "Designed over many iterations with Claude Code and Claude Design — from the 50-styles experiment to Stripe-inspired waves to the Liquid Glass system.",
    "stack": [
      "Claude Code",
      "Claude Design",
      "React",
      "View Transitions"
    ],
    "ergebnis": "Online soon — you're looking at a draft of it right now.",
    "zitat": "Your own website is the most honest project: no client, no excuses.",
    "learnings": "Relaunches fail from too many ideas — one clear system beats a hundred brainstorms.",
    "status": "online soon"
  },
  {
    "id": "du2016",
    "kind": "projekte",
    "kat": "Website",
    "tag": "REDESIGN",
    "datum": "03/2016",
    "name": "DesignUpdate 2016",
    "mono": "16",
    "color": "#0E7490",
    "featured": true,
    "link": "https://loona-designs.de",
    "linkLabel": "View live ↗",
    "tool": "Coda 2 · HTML5",
    "desc": "The Loona! redesign from 2016 — online since March 12, 2016, still in service today.",
    "ueberblick": "The platform's third big DesignUpdate — leaner, more responsive, content-focused. Still the live version of loona-designs.de today.",
    "ansatz": "Handcrafted in the editor (Coda 2 for Mac) — HTML5, CSS3 and deliberately little JavaScript.",
    "stack": [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Coda 2"
    ],
    "ergebnis": "Ten years in service — longevity as proof of quality.",
    "zitat": "Ten years online is the best Lighthouse score.",
    "learnings": "Simple tech ages most gracefully — the fewer dependencies, the longer a site lives.",
    "status": "online since 03/2016"
  },
  {
    "id": "du2015",
    "kind": "projekte",
    "kat": "Website",
    "tag": "REDESIGN",
    "datum": "04/2015",
    "name": "DesignUpdate 2015",
    "mono": "15",
    "color": "#155E75",
    "featured": false,
    "tool": "HTML5 · CSS3",
    "desc": "DesignUpdate 2015 — online from April 26, 2015.",
    "ueberblick": "The predecessor of today's design — a year of polish between two big updates.",
    "ansatz": "Iteration instead of a rebuild: typography, grid and color palette reworked, the foundation stayed.",
    "stack": [
      "HTML5",
      "CSS3",
      "JavaScript"
    ],
    "ergebnis": "Replaced by DesignUpdate 2016 after just under a year.",
    "zitat": "Some versions are bridges — important, even if you only cross them briefly.",
    "learnings": "Short iteration cycles on your own site keep the craft warm.",
    "status": "replaced 2016"
  },
  {
    "id": "du2011",
    "kind": "projekte",
    "kat": "Website",
    "tag": "REDESIGN",
    "datum": "08/2011",
    "name": "DesignUpdate 2011",
    "mono": "11",
    "color": "#1E3A5F",
    "featured": false,
    "tool": "XHTML · Railo",
    "desc": "DesignUpdate 2011 — online from August 19, 2011.",
    "ueberblick": "The first big redesign after saying goodbye to Flash — the platform moves into the HTML/CSS world.",
    "ansatz": "Away from Flash, toward clean markup — the zeitgeist of 2011, consistently executed.",
    "stack": [
      "XHTML",
      "CSS",
      "JavaScript",
      "ColdFusion / Railo"
    ],
    "ergebnis": "Four years online, then came 2015.",
    "zitat": "Saying goodbye to Flash was a fresh start.",
    "learnings": "Technology switches work best on your own project — before you recommend them to clients.",
    "status": "replaced 2015"
  },
  {
    "id": "autowerkstatt",
    "kind": "projekte",
    "kat": "Website",
    "tag": "CLIENT PROJECT",
    "datum": "2007–2012",
    "name": "Die Autowerkstatt",
    "mono": "AW",
    "color": "#374151",
    "featured": false,
    "tool": "XHTML · PHP",
    "desc": "Client website — five years online, from August 2007 to August 2012.",
    "ueberblick": "Website for an auto repair shop — services, contact, directions. Solid craftsmanship for a craft business.",
    "ansatz": "Classic structure with a focus on findability and easy maintenance.",
    "stack": [
      "XHTML",
      "CSS",
      "PHP"
    ],
    "ergebnis": "Five years reliably on the web.",
    "zitat": "Good tradesman websites are like good repair shops: unfussy and dependable.",
    "learnings": "Small client projects teach the essentials: listen, deliver, be patient.",
    "status": "online 2007–2012"
  },
  {
    "id": "cattshop",
    "kind": "projekte",
    "kat": "Shop",
    "tag": "CONCEPT",
    "datum": "2006",
    "name": "CATT Shop + CMS",
    "mono": "CS",
    "color": "#5B21B6",
    "featured": false,
    "tool": "Photoshop · PHP",
    "desc": "Online shop concept with its own CMS for the computer service CATT.",
    "ueberblick": "Shop concept with product view and a matching admin CMS — created as a concept.",
    "ansatz": "Design and system architecture from a single source — from screen design to data structure.",
    "stack": [
      "Photoshop",
      "XHTML",
      "PHP",
      "MySQL"
    ],
    "ergebnis": "It stayed a concept — the shop-system thinking stayed too.",
    "zitat": "Even unpublished work pays into the account.",
    "learnings": "Concepts are practice rooms: whoever designs shops later understands billing systems faster.",
    "status": "Concept"
  },
  {
    "id": "ld2006",
    "kind": "projekte",
    "kat": "Website",
    "tag": "PERSONAL PROJECT",
    "datum": "2006",
    "name": "Loona! Designs 'ld2006'",
    "mono": "06",
    "color": "#9A3412",
    "featured": false,
    "tool": "Flash · ActionScript 2",
    "desc": "The Loona! website from 2006 — splash screen, home page, about us.",
    "ueberblick": "The platform version from the year the company was founded — with a splash screen, as was proper in 2006.",
    "ansatz": "Flash-inspired aesthetics, loving details — the web as a stage.",
    "stack": [
      "Flash",
      "ActionScript 2",
      "XHTML"
    ],
    "ergebnis": "A time capsule of the Flash era — screenshots in the archive.",
    "zitat": "Splash screens were our View Transitions.",
    "learnings": "Aesthetics age, care doesn't — the attention to detail from 2006 still holds up today.",
    "status": "Archive"
  },
  {
    "id": "fahrschule",
    "kind": "projekte",
    "kat": "Design",
    "tag": "CONCEPT",
    "datum": "2006",
    "name": "Driving School (fictional)",
    "mono": "FS",
    "color": "#065F46",
    "featured": false,
    "tool": "Photoshop · XHTML",
    "desc": "Homepage concept for a fictional driving school — two home page variants.",
    "ueberblick": "Free design project: a driving school website that never existed — two variants of the home page.",
    "ansatz": "A finger exercise in layout and imagery, without a client brief.",
    "stack": [
      "Photoshop",
      "XHTML",
      "CSS"
    ],
    "ergebnis": "A portfolio piece from the early years.",
    "zitat": "Fictional clients are the most patient.",
    "learnings": "Free work shows your own signature more clearly than any brief.",
    "status": "Concept"
  },
  {
    "id": "catt2005",
    "kind": "projekte",
    "kat": "Website",
    "tag": "CLIENT PROJECT",
    "datum": "2005",
    "name": "CATT Service",
    "mono": "CT",
    "color": "#6D28D9",
    "featured": false,
    "tool": "XHTML · PHP",
    "desc": "Homepage for the computer service CATT.",
    "ueberblick": "Company website for a computer service — services and contact, clearly presented.",
    "ansatz": "Clean screen design, lean markup — craftsmanship from 2005.",
    "stack": [
      "XHTML",
      "CSS",
      "PHP"
    ],
    "ergebnis": "Online for several years; offline today.",
    "zitat": "Every client site is a small promise.",
    "learnings": "IT service providers as clients sharpen your own precision — they look at the details.",
    "status": "no longer online"
  },
  {
    "id": "hannoback",
    "kind": "projekte",
    "kat": "Website",
    "tag": "CLIENT PROJECT",
    "datum": "2005",
    "name": "Hannoback",
    "mono": "HB",
    "color": "#92400E",
    "featured": false,
    "tool": "PHP · MySQL",
    "desc": "Homepage with a custom-built MiniCMS for Hannoback.de.",
    "ueberblick": "Client website plus MiniCMS — editing your own content, long before that was a given.",
    "ansatz": "A small, tailor-made CMS instead of off-the-shelf software — exactly as much system as needed.",
    "stack": [
      "PHP",
      "MySQL",
      "XHTML"
    ],
    "ergebnis": "The client could edit content themselves — support effort close to zero.",
    "zitat": "The best CMS is the one the client understands.",
    "learnings": "Build tools to the user's measure — a lesson that carries from MiniCMS to WorkBench.",
    "status": "no longer online"
  },
  {
    "id": "yayci",
    "kind": "projekte",
    "kat": "Shop",
    "tag": "CLIENT PROJECT",
    "datum": "2004",
    "name": "Computer Handel Yayci",
    "mono": "YA",
    "color": "#1D4ED8",
    "featured": false,
    "tool": "PHP · MySQL",
    "desc": "A complete online shop — home page, categories, info bar.",
    "ueberblick": "A full online shop for a computer retailer — from the home page to the category overview.",
    "ansatz": "Shop logic, categories and admin built independently — 2004, without a framework safety net.",
    "stack": [
      "PHP",
      "MySQL",
      "XHTML",
      "CSS"
    ],
    "ergebnis": "The first big e-commerce job.",
    "zitat": "Without frameworks, you learn what frameworks do.",
    "learnings": "Building e-commerce from scratch makes every later shop system self-explanatory.",
    "status": "no longer online"
  },
  {
    "id": "cot2003",
    "kind": "projekte",
    "kat": "Game",
    "tag": "FLASH 5 GAME",
    "datum": "2003",
    "name": "Covert Operations Tournament",
    "mono": "CO",
    "color": "#166534",
    "featured": true,
    "tool": "Flash 5 · ActionScript",
    "desc": "Flash 5 game from 2003 — the ancestor of today's Covert Operations series.",
    "ueberblick": "A tournament shooter in Flash 5 — and the namesake: 23 years later, Covert Operations returns as an AI experiment.",
    "ansatz": "Timeline, MovieClips and ActionScript — game development with the tools of 2003.",
    "stack": [
      "Flash 5",
      "ActionScript"
    ],
    "ergebnis": "The start of a series that lives on in 2026.",
    "zitat": "Some ideas wait 23 years for their sequel.",
    "learnings": "Game feel is timeless — the tools change, the fascination doesn't.",
    "status": "Archive — sequel 2026"
  },
  {
    "id": "egermann",
    "kind": "projekte",
    "kat": "Website",
    "tag": "CLIENT PROJECT",
    "datum": "2002",
    "name": "RA Egermann",
    "mono": "RE",
    "color": "#334155",
    "featured": false,
    "tool": "HTML · CSS",
    "desc": "Homepage for a law firm — one of the first client projects.",
    "ueberblick": "Law firm website from 2002 — the start of client work, while still in training.",
    "ansatz": "Seriousness over gimmicks: clear structure, calm design.",
    "stack": [
      "HTML",
      "CSS"
    ],
    "ergebnis": "The first time being responsible for a professional's public presence.",
    "zitat": "Lawyers teach you diligence — inevitably.",
    "learnings": "Professional restraint is a design discipline, too.",
    "status": "no longer online"
  },
  {
    "id": "arena",
    "kind": "labs",
    "kat": "Game",
    "tag": "AI EXPERIMENT",
    "datum": "05/2026",
    "name": "Covert Operations Arena",
    "mono": "CA",
    "color": "#7F1D1D",
    "featured": true,
    "tool": "Claude Code · Opus 4.8",
    "desc": "The arena FPS spin-off of Covert Operations — faster, denser, louder.",
    "ueberblick": "The arena shooter spin-off of Covert Operations: smaller maps, higher pace.",
    "ansatz": "Continued as an experiment with Opus 4.8 — what does a model leap change about the development flow?",
    "stack": [
      "Claude Code",
      "Opus 4.8",
      "JavaScript"
    ],
    "ergebnis": "Work in progress — the workbench is open.",
    "zitat": "Speed is a feature — in the development process, too.",
    "learnings": "A model leap changes the dialog more than the code: sharper questions, shorter loops."
  },
  {
    "id": "deathgrid",
    "kind": "labs",
    "kat": "Game",
    "tag": "AI EXPERIMENT",
    "datum": "05/2026",
    "name": "Death Grid 3D",
    "mono": "DG",
    "color": "#18181B",
    "featured": true,
    "tool": "Antigravity 2",
    "desc": "Retro-style shooter in the finest Doom tradition — grid, sprites, adrenaline.",
    "ueberblick": "A retro shooter like Doom: raycasting aesthetics, sprites, pace.",
    "ansatz": "Experiment with Antigravity 2 — different tool, same question: how far does AI-assisted prototyping go?",
    "stack": [
      "Antigravity 2",
      "JavaScript",
      "Canvas"
    ],
    "ergebnis": "Work in progress.",
    "zitat": "Constraints from 1993, tools from 2026.",
    "learnings": "Retro aesthetics force clarity — in design as in code. Telling a story with few pixels teaches priorities."
  },
  {
    "id": "workbench",
    "kind": "labs",
    "kat": "Tool",
    "tag": "TOOL",
    "datum": "05/2026",
    "name": "LD WorkBench",
    "mono": "WB",
    "color": "#B45309",
    "featured": true,
    "tool": "Claude Code · Opus 4.7",
    "desc": "Managing timesheets and notes — the tool everyday life ordered.",
    "ueberblick": "Timesheets and notes in one place — the tool my own everyday life ordered.",
    "ansatz": "With Claude Code (Opus 4.7) from need to usable tool — personal need as the best requirements document.",
    "stack": [
      "Claude Code",
      "Opus 4.7",
      "React",
      "TypeScript"
    ],
    "ergebnis": "Work in progress — in daily personal use.",
    "zitat": "Personal need is the most honest requirements document.",
    "learnings": "Tools mature fastest when you have to put up with them yourself every day."
  },
  {
    "id": "buddy",
    "kind": "labs",
    "kat": "Tool",
    "tag": "TOOL",
    "datum": "03/2026",
    "name": "LD Buddy",
    "mono": "LB",
    "color": "#4C1D95",
    "featured": false,
    "tool": "Claude Code · Opus 4.5–4.7",
    "desc": "Managing finances, orders and more — the personal assistant.",
    "ueberblick": "The personal assistant: managing finances, orders and more.",
    "ansatz": "Grown across several Opus versions (4.5–4.7) — a long-term experiment in AI-assisted product development.",
    "stack": [
      "Claude Code",
      "Opus 4.5–4.7",
      "React"
    ],
    "ergebnis": "Work in progress.",
    "zitat": "An assistant is good when it's boringly reliable.",
    "learnings": "Building across model versions shows what really holds up: your own structure, not the tool."
  },
  {
    "id": "designideas",
    "kind": "labs",
    "kat": "Design",
    "tag": "DESIGN",
    "datum": "05/2026",
    "name": "LD Website Design Ideas",
    "mono": "LD",
    "color": "#F2E8D5",
    "featured": false,
    "tool": "Claude Code · Opus 4.8",
    "desc": "Design explorations for the new Loona! Designs website — this one.",
    "ueberblick": "Design explorations for the relaunch of loona-designs.de — the page you're looking at right now is one of the results.",
    "ansatz": "Think through many directions in parallel, filter ruthlessly — from the 50-styles experiment to the Stripe-inspired wave hero.",
    "stack": [
      "Claude Code",
      "Opus 4.8",
      "Design Systems"
    ],
    "ergebnis": "Work in progress — you're looking at it right now.",
    "zitat": "Fifty ideas, so that one remains.",
    "learnings": "Filtering ruthlessly is part of the design — not its failure. The path from 50 styles to one system was the real design."
  }
];

export const projectById = (id: string) => PROJECTS.find((p) => p.id === id);
export const projectsOf = (kind: ProjectKind) => PROJECTS.filter((p) => p.kind === kind);
